--- #YAML:1.0
name:               Range-Object
version:            0.92
abstract:           Manipulate ranges of different objects using the same API
author:
    - Alexander Tokarev <tokarev@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Range:   1.40
    Date::Simple:  3.00
    List::Util:    0
    Test::More:    0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Range-Object
    repository:  http://github.com/nohuhu/Range-Object
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
